name: JustKits
version: 1.2
main: io.github.gd402.justkits.JustKits
api-version: 1.16

commands:
  kit:
    description: Gives a specified kit to player
    usage: /kit
    permission: justkits.kit
  kits:
    description: Lists available kits from JustKits
    usage: /kits
    permission: justkits.kits